### ISSUE TITLE
Question: why is the event fired this way?

### ISSUE THREAD

**Issue by mercmobily** [PolymerElements/iron-form-element-behavior#27]
Hi,

From the [source](https://github.com/PolymerElements/iron-form-element-behavior/blob/master/iron-form-element-behavior.html#L78-L81):

```
detached: function() {
  if (this._parentForm) {
    this._parentForm.fire('iron-form-element-unregister', {target: this});
  }
```

Why is the event fired this way?
The element is actually fired by the `_parentForm` element, but then the `target` for it is set to the detached element itself?

Can you not do this:

```
detached: function() {
  if (this._parentForm) {
    this.fire('iron-form-element-unregister');
  }
```

Because the element is already detached at this point?

**Comment by notwaldorf** [comment]
It's fired like that so that the parent `<iron-form>`, which listens to this event, knows which element did the firing so that it can remove it from the list of elements it's tracking: https://github.com/PolymerElements/iron-form/blob/master/iron-form.html#L357

**Comment by mercmobily** [comment]
Hi,

Thank you!

Merc.
