### ISSUE TITLE
#2.0-preview branch please

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/iron-form-element-behavior#29]
@notwaldorf Humanity :earth_africa: 2.0 is counting on you 💃  Free them from the evil ☠️ 1.0 

Save us please :gift_heart:

```
"dependencies": {
    "polymer": "Polymer/polymer#2.0-preview",
    "webcomponentsjs": "#v1"
  },
  "devDependencies": {
    "iron-component-page": "PolymerElements/iron-component-page#2.0-preview"
  }
```

![image](https://cloud.githubusercontent.com/assets/863731/19098973/1fe8959c-8ab2-11e6-9bc2-69350c60dddf.png)

**Comment by notwaldorf** [comment]
Since `is=` is going away, `iron-form` is no longer a type extension but a wrapper element, and can just check it's distributed children -- which makes this behaviour not exactly needed. We're still discussing how to approach its 2.0 life, stay tuned.

**Comment by valdrinkoshi** [comment]
2.0 shipped \o/ We ended up deciding to not rely on iron-form-element-behavior in iron-form 2.x, so you don't need to implement this behavior to participate to forms in 2.x, but only have the properties `name/value` defined, and optionally `validate()` method to control validation. See more details at https://github.com/PolymerElements/iron-form/#changes-in-20
