### ISSUE TITLE
Exception in detached

### ISSUE THREAD

**Issue by morethanreal** [PolymerElements/iron-form-element-behavior#8]
Sorry I didn't catch this in the PR. `this._parentForm` is set to the parent node, which may or may not be a Polymer element and might not define the `fire` function.

**Comment by notwaldorf** [comment]
Gah, good catch. I'll fix this.

**Comment by jlg7** [comment]
+1 noticed this too! thanks for the report + pending fix!

**Comment by spirylics** [comment]
+1 pending fix too !
